### ISSUE TITLE
New feature: IMAP like WorkMail?

### ISSUE THREAD

**Issue by davi5e** [0x4447/0x4447_product_s3_email#31]
# My Problem

Is it / will it ever be possible to connect an IMAP Client (like Thunderbird) to handle S3 email?

# Solution

According to the [documentation](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/configure-email-client.html), there is a way to connect AWS SES to an email client, but I suppose there would be more to it, hence the question.

Not to mention how to go about authenticating users...

Regards, DAVI

**Comment by davidgatti** [comment]
No, because to do so you'd have to modify or make a IMAP server that knows how to read and write files to S3. You can connect SES to a email client only to send out emails. SES is a SMTP server not a IMAP or POP one. 

This project is not meant to replace a regular Email Server Setup. It was created to be a side solution not the main one.

**Comment by ben-xD** [comment]
It would be great if there was suggestions on what to use alongside with this project. If someone needed a mail server to access through POP/ IMAP, they would have to stop using this project as no servers access files through S3? It wouldn't be interoperable, would it? If there are no mail servers that can do the job of taking mail from S3, then this project is limited to emails that nobody thinks is important/ don't need to reply to? (e.g. notifications and confirmations aka emails you should just unsubscribe to).

- what do people actually use this project for? Do they browse the raw files in S3 for their emails? Hardly convenient. I know they can trigger notifications/ events based on writes on S3, but this is the only case I can think of. You mentioned in the README.

> When dealing with clients we came up with this folder structure:

But why don't you just send it a mail server that has POP/SMTP so that clients can actually load the emails. In this case, how does your staff actually read email from your clients? Do you forward the email, in this case you don't need S3.

**Comment by davidgatti** [comment]
I use https://www.panic.com/transmit/ to check the emails. Any S3 browser will do. Again this is not a replacement for regular email, not sure why this is so hard to get ;) 

And why I'm not forwarding them, because this is not a feature I care about, I don't want to get this emails. If I want to get those email to my main email, then I use my main email.
