### ISSUE TITLE
New feature: Programmatic addresses

### ISSUE THREAD

**Issue by iBobik** [0x4447/0x4447_product_s3_email#35]
# My Problem

On the same domain I want to have email address (e.g. forum-*@example.com) what is send directly to our system (e.g. Discourse forum). Emails send to this address should be immediatelly send by HTTP to an app endpoint (by a Lambda what will transform it to the right format).

# Solution

At least document how to configure custom Lambda processing specific address prefix to not break anything for 0x4447_product_s3_email.

Ideally have support for it. E.g. config what will turn off processing for some prefix but runs specific lambda.

**Comment by iBobik** [comment]
Btw, docs about how to not break things would be helpful also for integrating with some lambda email forwarder.

**Comment by davidgatti** [comment]
Hmmm, let see if I got what you are trying to say: You would like to trigger a API call to specific 3th party, if a message arrives to a specific email address. 

And if this is not possible to do, you would like to have a tutorial how to edit the project in a way that dose not brake the whole setup. 

If this is correct then:

- adding support for API call is a no go. Technically it would be possible but that would become e completely separate project that has nothing to do with this one, and will create to much complexity.
- Adding a tutorial how to modify your own lambda while preserving the functionality, would also be hard. Since there are endless possibilities, and make a tutorial for each one would be an infinite task.

What you are asking is a cool idea, but truly as a separate project, where incoming emails would be send to 3th parties over HTTPS. But also it would be quite the work, because for each 3th party you'd have to create a custom configuration, to make the correct API call for each service that you want to integrate with. End storing all all the credentials etc. 

If you are developer yourself, I'd just do this for ourself. Especially if you just need to support one service. 

You can reference this project, see how the SES needs to be setup, how the lambda is triggered, and what you put in your lambda it is up to you. This is all you need to make it work.

I hope this helps.

**Comment by iBobik** [comment]
Thank your for reply.

At least your great project will be useable as examples for my solution. :-)
